-- =====================================================
-- EVENTS & CATERING SCHEMA
-- =====================================================
-- Tables for private event planning and catering orders
-- with smart recommendations and document parsing
-- =====================================================

-- Events master table
CREATE TABLE IF NOT EXISTS events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    event_name TEXT NOT NULL,
    event_type TEXT CHECK(event_type IN (
        'wedding_reception', 'corporate_lunch', 'birthday_party',
        'anniversary', 'holiday_party', 'cocktail_party', 'fundraiser', 'other'
    )),
    event_date DATE NOT NULL,
    event_time TEXT,
    duration_hours REAL DEFAULT 4,
    guest_count INTEGER NOT NULL,
    guest_count_confirmed INTEGER,
    venue_type TEXT CHECK(venue_type IN ('on_site', 'off_site', 'outdoor')),
    venue_name TEXT,
    status TEXT CHECK(status IN ('planning', 'confirmed', 'in_progress', 'completed', 'cancelled')) DEFAULT 'planning',
    budget_cents INTEGER,
    estimated_cost_cents INTEGER,
    actual_cost_cents INTEGER,
    revenue_cents INTEGER,
    contact_name TEXT,
    contact_email TEXT,
    contact_phone TEXT,
    dietary_vegetarian INTEGER DEFAULT 0,
    dietary_vegan INTEGER DEFAULT 0,
    dietary_gluten_free INTEGER DEFAULT 0,
    dietary_other TEXT,
    notes TEXT,
    special_requests TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_events_user_date ON events(user_id, event_date);
CREATE INDEX IF NOT EXISTS idx_events_status ON events(status, event_date);
CREATE INDEX IF NOT EXISTS idx_events_type ON events(event_type);

-- Items needed for events
CREATE TABLE IF NOT EXISTS event_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    event_id INTEGER NOT NULL,
    inventory_item_id INTEGER,
    item_name TEXT NOT NULL,
    category TEXT,
    quantity_needed REAL NOT NULL,
    quantity_ordered REAL DEFAULT 0,
    unit_of_measure TEXT DEFAULT 'each',
    unit_cost_cents INTEGER,
    estimated_cost_cents INTEGER,
    actual_cost_cents INTEGER,
    vendor_name TEXT,
    is_ordered INTEGER DEFAULT 0,
    order_by_date DATE,
    notes TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
    FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id)
);

CREATE INDEX IF NOT EXISTS idx_event_items_event ON event_items(event_id);
CREATE INDEX IF NOT EXISTS idx_event_items_inventory ON event_items(inventory_item_id);

-- Catering orders
CREATE TABLE IF NOT EXISTS catering_orders (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    event_id INTEGER,
    order_name TEXT NOT NULL,
    order_type TEXT CHECK(order_type IN ('drop_off', 'full_service', 'pickup', 'buffet', 'plated', 'box_lunch')),
    order_date DATE NOT NULL,
    delivery_time TEXT,
    delivery_address TEXT,
    guest_count INTEGER NOT NULL,
    per_person_budget_cents INTEGER,
    total_cost_cents INTEGER,
    selling_price_cents INTEGER,
    profit_cents INTEGER,
    profit_margin_pct REAL,
    status TEXT CHECK(status IN ('draft', 'quoted', 'confirmed', 'preparing', 'delivered', 'completed', 'cancelled')) DEFAULT 'draft',
    contact_name TEXT,
    contact_email TEXT,
    contact_phone TEXT,
    company_name TEXT,
    dietary_notes TEXT,
    setup_instructions TEXT,
    pickup_time TEXT,
    staff_needed INTEGER DEFAULT 0,
    equipment_needed TEXT,
    notes TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (event_id) REFERENCES events(id)
);

CREATE INDEX IF NOT EXISTS idx_catering_user_date ON catering_orders(user_id, order_date);
CREATE INDEX IF NOT EXISTS idx_catering_status ON catering_orders(status);

-- Catering order items
CREATE TABLE IF NOT EXISTS catering_order_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    catering_order_id INTEGER NOT NULL,
    inventory_item_id INTEGER,
    item_name TEXT NOT NULL,
    category TEXT,
    quantity REAL NOT NULL,
    unit_of_measure TEXT DEFAULT 'serving',
    unit_cost_cents INTEGER,
    total_cost_cents INTEGER,
    selling_price_per_unit_cents INTEGER,
    total_selling_price_cents INTEGER,
    is_prepared INTEGER DEFAULT 0,
    notes TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (catering_order_id) REFERENCES catering_orders(id) ON DELETE CASCADE,
    FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id)
);

CREATE INDEX IF NOT EXISTS idx_catering_items_order ON catering_order_items(catering_order_id);

-- Event recommendations (generated by AI)
CREATE TABLE IF NOT EXISTS event_recommendations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    event_id INTEGER,
    catering_order_id INTEGER,
    recommendation_type TEXT CHECK(recommendation_type IN (
        'quantity_adjustment', 'bulk_opportunity', 'timing_alert',
        'cost_savings', 'historical_insight', 'dietary_reminder',
        'vendor_suggestion', 'staffing_suggestion'
    )),
    priority TEXT CHECK(priority IN ('critical', 'high', 'medium', 'low')),
    title TEXT NOT NULL,
    description TEXT,
    suggested_action TEXT,
    item_name TEXT,
    current_quantity REAL,
    suggested_quantity REAL,
    potential_savings_cents INTEGER DEFAULT 0,
    confidence_score REAL,
    reasoning TEXT,
    is_dismissed INTEGER DEFAULT 0,
    is_actioned INTEGER DEFAULT 0,
    actioned_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (event_id) REFERENCES events(id),
    FOREIGN KEY (catering_order_id) REFERENCES catering_orders(id)
);

CREATE INDEX IF NOT EXISTS idx_event_recs_user ON event_recommendations(user_id, is_dismissed, is_actioned);
CREATE INDEX IF NOT EXISTS idx_event_recs_event ON event_recommendations(event_id);
CREATE INDEX IF NOT EXISTS idx_event_recs_catering ON event_recommendations(catering_order_id);

-- Uploaded event documents
CREATE TABLE IF NOT EXISTS event_uploads (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    event_id INTEGER,
    catering_order_id INTEGER,
    user_id INTEGER NOT NULL,
    file_name TEXT NOT NULL,
    file_type TEXT,
    file_size_bytes INTEGER,
    original_text TEXT,
    parsed_guest_count INTEGER,
    parsed_event_date TEXT,
    parsed_items TEXT,
    parsed_dietary TEXT,
    parsed_budget_cents INTEGER,
    parsing_confidence REAL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (event_id) REFERENCES events(id),
    FOREIGN KEY (catering_order_id) REFERENCES catering_orders(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_event_uploads_event ON event_uploads(event_id);
CREATE INDEX IF NOT EXISTS idx_event_uploads_catering ON event_uploads(catering_order_id);

-- Event history for learning
CREATE TABLE IF NOT EXISTS event_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    event_id INTEGER NOT NULL,
    event_type TEXT,
    guest_count_planned INTEGER,
    guest_count_actual INTEGER,
    items_count INTEGER,
    total_cost_cents INTEGER,
    revenue_cents INTEGER,
    profit_cents INTEGER,
    waste_pct REAL,
    satisfaction_rating INTEGER,
    lessons_learned TEXT,
    notes TEXT,
    recorded_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (event_id) REFERENCES events(id)
);

CREATE INDEX IF NOT EXISTS idx_event_history_user_type ON event_history(user_id, event_type);

-- Event templates (pre-built and user-created)
CREATE TABLE IF NOT EXISTS event_templates (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER,
    template_name TEXT NOT NULL,
    event_type TEXT,
    default_guest_count INTEGER,
    default_duration_hours REAL DEFAULT 4,
    description TEXT,
    default_items TEXT,
    default_dietary_options TEXT,
    default_budget_per_person_cents INTEGER,
    is_system_template INTEGER DEFAULT 0,
    usage_count INTEGER DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_event_templates_type ON event_templates(event_type, is_system_template);

-- Insert system templates
INSERT OR IGNORE INTO event_templates (id, template_name, event_type, default_guest_count, default_duration_hours, description, default_items, is_system_template) VALUES
(1, 'Wedding Reception', 'wedding_reception', 100, 5, 'Full service wedding reception with cocktail hour, dinner, and dancing', '[{"category":"wine","name":"House Wine","quantity_per_guest":0.5},{"category":"champagne","name":"Champagne Toast","quantity_per_guest":0.3},{"category":"spirits","name":"Premium Bar","quantity_per_guest":0.15},{"category":"appetizers","name":"Passed Appetizers","quantity_per_guest":6},{"category":"entrees","name":"Plated Dinner","quantity_per_guest":1},{"category":"desserts","name":"Wedding Cake","quantity_per_guest":1}]', 1),
(2, 'Corporate Lunch', 'corporate_lunch', 50, 2, 'Business lunch meeting with light beverages and buffet', '[{"category":"beverages","name":"Coffee/Tea Service","quantity_per_guest":2},{"category":"appetizers","name":"Light Starters","quantity_per_guest":3},{"category":"entrees","name":"Buffet Lunch","quantity_per_guest":1},{"category":"desserts","name":"Mini Desserts","quantity_per_guest":1}]', 1),
(3, 'Birthday Party', 'birthday_party', 30, 3, 'Casual birthday celebration with cake and refreshments', '[{"category":"beer","name":"Craft Beer","quantity_per_guest":1.5},{"category":"wine","name":"Wine Selection","quantity_per_guest":0.3},{"category":"appetizers","name":"Party Snacks","quantity_per_guest":5},{"category":"entrees","name":"Casual Bites","quantity_per_guest":1},{"category":"desserts","name":"Birthday Cake","quantity_per_guest":1.2}]', 1),
(4, 'Cocktail Party', 'cocktail_party', 75, 3, 'Evening cocktail reception with heavy appetizers', '[{"category":"spirits","name":"Full Bar","quantity_per_guest":0.2},{"category":"wine","name":"Wine Selection","quantity_per_guest":0.4},{"category":"beer","name":"Craft Beer","quantity_per_guest":0.5},{"category":"appetizers","name":"Heavy Hors doeuvres","quantity_per_guest":10}]', 1),
(5, 'Holiday Party', 'holiday_party', 60, 4, 'Festive holiday celebration with full service', '[{"category":"champagne","name":"Sparkling Wine","quantity_per_guest":0.4},{"category":"wine","name":"Holiday Wines","quantity_per_guest":0.5},{"category":"spirits","name":"Seasonal Cocktails","quantity_per_guest":0.15},{"category":"appetizers","name":"Holiday Appetizers","quantity_per_guest":7},{"category":"entrees","name":"Holiday Buffet","quantity_per_guest":1},{"category":"desserts","name":"Dessert Bar","quantity_per_guest":1.3}]', 1);
