# =====================================================
# DIGITALOCEAN APP PLATFORM CONFIGURATION
# =====================================================
# This file tells DigitalOcean how to deploy your app
# automatically from GitHub

name: revenue-radar
region: nyc

services:
  - name: revenue-radar-api
    # Build configuration
    github:
      repo: YOUR_GITHUB_USERNAME/revenue-radar
      branch: main
      deploy_on_push: true

    # Runtime environment
    environment_slug: node-js

    # Resource size (basic = $12/month)
    instance_size_slug: basic-xxs
    instance_count: 1

    # HTTP port configuration
    http_port: 5050

    # Health check endpoint
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    # Build command
    build_command: npm install

    # Start command
    run_command: npm start

    # Environment variables
    envs:
      - key: NODE_ENV
        value: production

      - key: PORT
        value: "5050"

      # These will be set in DigitalOcean console (encrypted)
      - key: ANTHROPIC_API_KEY
        scope: RUN_TIME
        type: SECRET

      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET

      - key: SESSION_SECRET
        scope: RUN_TIME
        type: SECRET

      - key: DATABASE_PATH
        value: /data/revenue-radar.db

      - key: DATABASE_BACKUP_PATH
        value: /data/backups

      - key: DATABASE_BACKUP_ENABLED
        value: "true"

      - key: DATABASE_BACKUP_INTERVAL_HOURS
        value: "12"

      - key: DATABASE_BACKUP_RETENTION_DAYS
        value: "30"

      - key: ALLOWED_ORIGINS
        value: https://your-domain.com,https://www.your-domain.com

      - key: TRUST_PROXY
        value: "true"

      - key: BCRYPT_ROUNDS
        value: "12"

      - key: MAX_FAILED_LOGIN_ATTEMPTS
        value: "5"

      - key: ACCOUNT_LOCKOUT_MINUTES
        value: "15"

      - key: JWT_EXPIRES_IN
        value: 24h

      - key: REFRESH_TOKEN_EXPIRES_IN
        value: 30d

      - key: RATE_LIMIT_WINDOW_MS
        value: "60000"

      - key: RATE_LIMIT_MAX_REQUESTS
        value: "100"

      - key: WEB_SCRAPER_ENABLE
        value: "1"

      - key: OSM_ENABLE
        value: "1"

# Persistent storage for database and backups
databases:
  # Using DigitalOcean managed database is recommended for production
  # but we'll start with file-based SQLite on persistent storage

# Note: For production, consider upgrading to:
# - Managed PostgreSQL database ($15/month)
# - Managed Redis for session storage ($15/month)
# - Spaces for backup storage ($5/month)
